import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/footer";
import { Directions, Languages } from "@/constants/enums";
import { Locale } from "@/i18n.config";
import ReduxProvider from "@/providers/ReduxProvider";
import { Metadata } from "next";
import { Cairo, Roboto } from "next/font/google";

export const metadata: Metadata = {
  title: "Food Ordering App",
  description: "Generated by Faisal Abu Zakari",
};
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  // here i use preload to load the font before the page is loaded
  preload: true,
});
const cairo = Cairo({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: true,
});

// الفنشكن هتعمل انشاء للصفحات العربية و الانجليزية فقط , لانه داينميك راوت يبقى بيقدر يكتب اي حاجة و هيك بتصير خطأ
// لذلك انا حددت اله انه فقط عربي او انجليزي يلي تعمل الهم انشاء
export async function generateStaticParams() {
  return [{ locale: Languages.ARABIC }, { locale: Languages.ENGLISH }];
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>;
}>) {
  const locale = (await params).locale;
  return (
    <html
      lang={locale}
      dir={locale === Languages.ARABIC ? Directions.RTL : Directions.LTR}
    >
      {/* i use tailwind css , so i will className keyword to apply the font */}
      <body
        className={
          locale === Languages.ARABIC ? cairo.className : roboto.className
        }
      >
        <ReduxProvider>
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
